### ISSUE TITLE
Tighter body checks

### ISSUE THREAD

**Issue by srittau** [ambv/flake8-pyi#29]
Y010 currently allows raise statements and assignments in `__init__`. Since I just stumbled about a few raise statements in typeshed, I'd like a tighter version of this check that disallows anything but `...`.

**Comment by JelleZijlstra** [comment]
I allowed those because they appeared in typeshed when I wrote the check, and I assumed (possibly incorrectly) that pytype did something  useful with the raise statements.

Assignments I believe are allowed because some typeshed stubs were setting attributes in `__init__` methods. If there are no instances of that left, we can tighten the check.

**Comment by srittau** [comment]
It seems typeshed still has a few raises left:

```
$ rgrep " raise " stdlib/ third_party/ | wc -l
81
```

**Comment by srittau** [comment]
typeshed will pass both Y090 and Y091 when python/typeshed#3355 gets merged. Depending on whether backwards compatibility matters for flake8-pyi they could get merged back into Y010 or be enabled by default.

**Comment by JelleZijlstra** [comment]
I think we should make it a separate check because my understanding is that there are a few users outside of typeshed and they might be unhappy to get this new check.
