### ISSUE TITLE
Check for missing generic arguments

### ISSUE THREAD

**Issue by srittau** [ambv/flake8-pyi#42]
For example `foo: Pattern` instead of `foo: Pattern[str]` or `foo: Pattern[Any]`.

**Comment by JelleZijlstra** [comment]
I'm not sure this is a good fit for flake8 because the linter doesn't know what classes are generic. mypy already supports this, with the `--disallow-any-generics` option and we have that option on in our test (https://github.com/python/typeshed/blob/master/tests/mypy_test.py#L133), so perhaps there's a bug in mypy that caused `Pattern` to be missed.

**Comment by srittau** [comment]
Sounds reasonable.
